obj-$(CONFIG_CLUSTER_PLUG)	:= cluster_plug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
obj-$(CONFIG_ASMP)		+= autosmp.o 
obj-$(CONFIG_MAKO_HOTPLUG) 	+= mako_hotplug.o
obj-$(CONFIG_MSM_SLEEPER) 	+= msm_sleeper.o

